### ISSUE TITLE
As a user, I want to format tokens according to a configuration, so that I can format code according to standards

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/AnalyzerRules#17]
### Story Type

User

### Definition of Done

PSScriptAnalyzer uses the Settings for case values of configured token types.

### Tasks

- [ ] Create test functions for each type of case
- [ ] Create conversion functions for each type of case
- [ ] Create rules for each type of token
- [ ] Create standard settings for token types
